import {
  BadRequestException,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Docente } from './entities/docente.entity';
import { CreateDocenteDto, UpdateDocenteDto } from './dto/docente.dto';

@Injectable()
export class DocentesService {
  constructor(
    @InjectRepository(Docente)
    private readonly docenteRepository: Repository<Docente>,
  ) {}

  async create(createDocenteDto: CreateDocenteDto): Promise<Docente> {
    try {
      //check if docente was soft deleted
      const deletedDocente = await this.findDeletedDocenteByDni(
        createDocenteDto.dni,
      );

      // if was deleted, restore
      if (deletedDocente) {
        await this.docenteRepository.restore(deletedDocente.id);
        return deletedDocente;
      }

      // if not, create
      const newDocente = this.docenteRepository.create(createDocenteDto);
      return await this.docenteRepository.save(newDocente);
    } catch (error) {
      if (error.errno === 1062) {
        throw new BadRequestException(
          `El docente con dni: ${createDocenteDto.dni} ya existe.`,
        );
      }
      throw error;
    }
  }

  async findAll(): Promise<Docente[]> {
    // const hola = [
    //   { dni: '39525434', lastname: 'VILCHEZ', name: ' MARIA GUADALUPE' },
    //   { dni: '44479198', lastname: 'ORTIZ MONTAÑO YANEL', name: ' MILENA' },
    //   { dni: '44061433', lastname: 'CORTEZ BRIZUELA', name: ' ANA PAULA' },
    //   { dni: '35848818', lastname: 'SIERRA', name: ' CAROLINA MARISOL' },
    //   { dni: '39183972', lastname: 'LUCERO', name: ' MARIANELA AYELEN' },
    //   { dni: '34243125', lastname: 'TAPIA', name: ' LAURA MELINA' },
    //   {
    //     dni: '44061525',
    //     lastname: 'HERNANDEZ MARTINEZ',
    //     name: ' CAMILA AYELEN',
    //   },
    //   { dni: '42250343', lastname: 'CHAVES MORENO', name: ' LAURA NOEMI' },
    //   { dni: '35506887', lastname: 'CASTRO CASTRO', name: ' IVANA MARIA' },
    //   {
    //     dni: '42207398',
    //     lastname: 'BALMACEDA LEVIS',
    //     name: ' SASHA JAQUELINE',
    //   },
    //   {
    //     dni: '35148447',
    //     lastname: 'OCHOA RAMIREZ',
    //     name: ' IVANNA YESICA CELINDA',
    //   },
    //   { dni: '43838483', lastname: 'FERNANDEZ', name: ' DANIELA JUDITH' },
    //   { dni: '32693477', lastname: 'ILLANES', name: ' MARIA JOSE' },
    //   { dni: '36051417', lastname: 'GARCIA', name: ' MARIA BELEN' },
    //   { dni: '35850815', lastname: 'GARCIA COMELLI', name: ' MAIRA MICAELA' },
    //   { dni: '32718825', lastname: 'BIAZZETTI', name: ' ROMINA MARISOL' },
    //   {
    //     dni: '37506743',
    //     lastname: 'MOLINA DALESIO',
    //     name: ' ELIANA ELISABETH',
    //   },
    //   {
    //     dni: '31388938',
    //     lastname: 'DI CARLO MENENDEZ',
    //     name: ' YANINA VANESA',
    //   },
    //   { dni: '33672441', lastname: 'ARREDONDO', name: ' CARLA YANEL' },
    //   { dni: '35922649', lastname: 'MONLA VERA', name: ' TAIEL ITAMAR' },
    //   {
    //     dni: '41122508',
    //     lastname: 'PASTRAN RODRIGUEZ',
    //     name: ' CINTIA DAYANA',
    //   },
    //   { dni: '36252298', lastname: 'CORVALAN', name: ' PAMELA NOELIA' },
    //   { dni: '34921194', lastname: 'MOREIRA PAEZ', name: ' NATALIE YAMILA' },
    //   {
    //     dni: '39425876',
    //     lastname: 'GALLARDO AMOROS',
    //     name: ' MARIA ROSA CELIA',
    //   },
    //   { dni: '35023667', lastname: 'GAMBA SEGOVIA', name: ' OSCAR ENRIQUE' },
    //   { dni: '38594029', lastname: 'CABRERA', name: ' MARIA BELEN' },
    //   { dni: '29883440', lastname: 'BARRERA', name: ' PAOLA MARINA' },
    //   { dni: '44674843', lastname: 'GUEVARA CABALLERO', name: ' KAROL MORENA' },
    //   { dni: '42081098', lastname: 'LEIVA PUIG', name: ' MARIA DEL MILAGRO' },
    //   { dni: '36612630', lastname: 'ROLDAN', name: ' JESSICA LUCIA' },
    //   { dni: '30872488', lastname: 'CORTEZ ALE', name: ' GLADYS' },
    //   { dni: '31044254', lastname: 'SASO BRIZUELA', name: ' CAROLINA BELEN' },
    //   { dni: '36032434', lastname: 'BALMACEDA', name: ' DAIANA ANTONELA' },
    //   { dni: '39007386', lastname: 'AZCURRA', name: ' GEMA DEL VALLE' },
    //   { dni: '38460115', lastname: 'AGUERO', name: ' YESICA DEL VALLE' },
    //   { dni: '38463723', lastname: 'GONZALEZ ANDRADA', name: ' ROSA YAMILA' },
    //   { dni: '35356104', lastname: 'CALDERON', name: ' DAIANA BELEN' },
    //   { dni: '39956223', lastname: 'AGUIRRE', name: ' ROMINA EMMA' },
    //   {
    //     dni: '42853348',
    //     lastname: 'RECABARREN MERCADO',
    //     name: ' YESICA ARACELI',
    //   },
    //   { dni: '29621063', lastname: 'RONDA LUNA', name: ' MARIA SOL' },
    //   { dni: '35924524', lastname: 'GOMEZ', name: ' CINTIA DEL VALLE' },
    //   { dni: '42852908', lastname: 'MENDEZ', name: ' CAMILA ISABEL' },
    //   {
    //     dni: '42918480',
    //     lastname: 'SIERRA NAVEDA',
    //     name: ' SOLANGE LISETH SIERRA NAVEDA',
    //   },
    //   {
    //     dni: '40779566',
    //     lastname: 'FELICITO BENEGAS',
    //     name: ' MARIA DEL MILAGRO',
    //   },
    //   { dni: '36032750', lastname: 'PAEZ', name: ' SHEILA CECILIA' },
    //   { dni: '38463599', lastname: 'RODRIGUEZ', name: ' MARIA SOL' },
    //   { dni: '38460478', lastname: 'MOYA LUCERO', name: ' MADELEIN DESIRE' },
    //   { dni: '43123026', lastname: 'MOYANO', name: ' MARTINA CONCEPCIÓN' },
    //   { dni: '34711529', lastname: 'CORTEZ FARIAS', name: ' MARGARITA NOEMI' },
    //   { dni: '39424253', lastname: 'LOPEZ HEREDIA', name: ' TATIANA JANET' },
    //   { dni: '35857589', lastname: 'RIVEROS', name: ' YESICA ANALIA' },
    //   { dni: '36254233', lastname: 'PEREZ BRAVO', name: ' ANA AYELEN' },
    //   { dni: '34054907', lastname: 'VARAS OLMOS', name: ' MARIA CELIA' },
    //   { dni: '40368871', lastname: 'PRADO VALVERDE', name: ' KARINA NATALIA' },
    //   {
    //     dni: '40469590',
    //     lastname: 'MONTENEGRO MARINERO',
    //     name: ' MARIA LAURA',
    //   },
    //   { dni: '29427389', lastname: 'GODOY', name: ' DEOLINDA MARIBEL' },
    //   {
    //     dni: '35856843',
    //     lastname: 'ORTIZ QUINTEROS',
    //     name: ' CINTIA PAOLA EDITH',
    //   },
    //   { dni: '44761442', lastname: 'TORRES CALVO', name: ' MAYRA AYELEN' },
    //   { dni: '31871565', lastname: 'COMELLI', name: ' PAMELA ANDREA' },
    //   { dni: '31888196', lastname: 'HERRERA GALDEANO', name: ' MARIA VANESA' },
    //   {
    //     dni: '31888037',
    //     lastname: 'PELAYES CHACON',
    //     name: ' FLABIA ELIZABETH',
    //   },
    //   { dni: '30631149', lastname: 'SILVA NARANJO', name: ' LETICIA ANABEL' },
    //   { dni: '44060752', lastname: 'GONZALEZ VARELA', name: ' ANA VALENTINA' },
    //   { dni: '38074365', lastname: 'TORRES-SORIA', name: ' ELIDA EVA' },
    //   { dni: '42163459', lastname: 'TORRES CALVO', name: ' KAREN TAMARA' },
    //   { dni: '29264900', lastname: 'ROSALES BENEGAS', name: ' VALERIA PAOLA' },
    //   { dni: '41468416', lastname: 'MUÑOZ', name: ' MAIRA CELESTE' },
    //   { dni: '30157764', lastname: 'PES', name: ' VANESA RENEE' },
    //   { dni: '42516238', lastname: 'ESCUDERO', name: ' PAMELA SOLANGE' },
    //   { dni: '36031420', lastname: 'SOSA', name: ' CECILIA' },
    //   {
    //     dni: '34916829',
    //     lastname: 'ROSELLO QUIROGA',
    //     name: ' CINTHIA VERONICA',
    //   },
    //   { dni: '41221015', lastname: 'RIOS', name: ' SELENE BELEN' },
    //   { dni: '42712069', lastname: 'DIAZ QUIROGA', name: ' MADELEIN GISELLA' },
    //   { dni: '30343729', lastname: 'SILVA', name: ' ANDREA CARINA' },
    //   { dni: '43689894', lastname: 'GORDILLO', name: ' ANA PAULA' },
    //   { dni: '44633885', lastname: 'NUÑEZ', name: ' MICAELA ALEJANDRA' },
    //   { dni: '34329002', lastname: 'LARA', name: ' AGUSTIN' },
    //   {
    //     dni: '41830098',
    //     lastname: 'ALLENDE ENRIQUE',
    //     name: ' CARLOS EMILIANO',
    //   },
    //   {
    //     dni: '41809413',
    //     lastname: 'JORQUERA ESQUIVEL',
    //     name: ' XIMENA DANISA',
    //   },
    //   { dni: '38363489', lastname: 'CARRIÓN', name: ' YESICA' },
    //   {
    //     dni: '42853230',
    //     lastname: 'LIMA ONTIVEROS',
    //     name: ' AGUSTINA FLORENCIA',
    //   },
    //   { dni: '35924148', lastname: 'ATAMPIZ', name: ' MAURO RODRIGO' },
    //   { dni: '38461881', lastname: 'RAMOS', name: ' MARIA EVELYN' },
    //   { dni: '44633797', lastname: 'ERASO', name: ' MICAELA SILVIA' },
    //   { dni: '37646590', lastname: 'CABALLERO', name: ' MELINA IVETH' },
    //   { dni: '44761456', lastname: 'VERAGUA', name: ' MATIAS' },
    //   { dni: '30840545', lastname: 'MARQUEZ', name: ' CLAUDIA FABIOLA' },
    //   { dni: '33715228', lastname: 'CHAVEZ', name: ' FERNANDA DANIELA' },
    //   { dni: '43157512', lastname: 'LUCARÁS OTAROLA', name: ' LEONARDO JESÚS' },
    //   { dni: '34915687', lastname: 'OJEDA', name: ' VALERIA ELIZABETH' },
    //   { dni: '35508690', lastname: 'NESMAN', name: ' ALISON' },
    //   { dni: '36768045', lastname: 'PEREYRA', name: ' ROMINA AGUSTINA' },
    //   { dni: '38595001', lastname: 'OVIEDO', name: ' CARLA CELINA' },
    //   { dni: '33460785', lastname: 'FIORANELLI', name: ' YANINA PAOLA' },
    //   { dni: '42632969', lastname: 'VEGA LARA', name: ' CELENE MARIAN' },
    //   { dni: '35736171', lastname: 'ACIAR', name: ' ROCIO GISEL' },
    //   { dni: '34697332', lastname: 'MUÑOZ DIAZ', name: ' GABRIELA ANABEL' },
    //   { dni: '44316041', lastname: 'SALICA ZEBALLOS', name: ' MARISOL' },
    //   { dni: '40823802', lastname: 'GARCIA', name: ' MAIRA BELEN' },
    //   {
    //     dni: '44248982',
    //     lastname: 'ROSALES PEÑALOZA',
    //     name: ' PRISCILA BELEN',
    //   },
    //   { dni: '34920536', lastname: 'ARRECHEA', name: ' EDUARDO MANUEL' },
    //   { dni: '33672411', lastname: 'GONZALEZ', name: ' MARIA BETSABE' },
    //   { dni: '43555379', lastname: 'GALLERANO', name: ' ROCIO LUZ' },
    //   { dni: '23977036', lastname: 'MERCADO', name: ' ELIANA VERONICA' },
    //   {
    //     dni: '40728769',
    //     lastname: 'ORDENES QUIROGA',
    //     name: ' ALEJANDRA DANIELA',
    //   },
    //   { dni: '39525068', lastname: 'GOMEZ', name: ' ANA LAURA' },
    //   { dni: '38461283', lastname: 'ADARO MILLA', name: ' FABIAN EVER' },
    //   {
    //     dni: '42235020',
    //     lastname: 'GONZALEZ CORICA',
    //     name: ' ROCIO DE LOS ANGELES',
    //   },
    //   { dni: '36424134', lastname: 'MOREIRA MARTI', name: ' ESEQUIEL MATIAS' },
    //   { dni: '33836342', lastname: 'BAZAN', name: ' NIDIA FATIMA' },
    //   {
    //     dni: '37924693',
    //     lastname: 'RODRIGUEZ ESQUIBEL',
    //     name: ' MELISA LIDIA',
    //   },
    //   { dni: '44317344', lastname: 'HIDALGO MONTAÑA', name: ' MACARENA' },
    //   { dni: '30835951', lastname: 'CHELI', name: ' ANGEL OMAR' },
    //   { dni: '44061164', lastname: 'CAYLLET', name: ' AGUSTINA NOEL' },
    //   { dni: '31654401', lastname: 'ARREDONDO', name: ' JESICA CAROLINA' },
    //   { dni: '39994951', lastname: 'BONDANZA', name: ' SOFIA MICAELA' },
    //   { dni: '42163250', lastname: 'AGUERO CANTO', name: ' BRAIAN EXEQUIEL' },
    //   { dni: '42451859', lastname: 'RODRIGUEZ', name: ' MARLEN AYELEN' },
    //   { dni: '44127884', lastname: 'DIAZ  GARCIA', name: ' MARTINA  BELEN' },
    //   { dni: '35734810', lastname: 'SALINAS GARAY', name: ' AIDA NATALIA' },
    //   { dni: '44479356', lastname: 'MANZANO', name: ' CINTIA BELEN' },
    //   { dni: '38461283', lastname: 'ADARO MILLA', name: ' FABIAN EVER' },
    //   { dni: '34696915', lastname: 'MORETA SEVILLA', name: ' MARIA AGUSTINA' },
    //   { dni: '25195044', lastname: 'ZABALETA', name: ' ALEJANDRO DANIEL' },
    //   { dni: '29888899', lastname: 'MAZUELOS', name: ' MARIA LAURA VICTORIA' },
    //   { dni: '43422972', lastname: 'COSTA', name: ' CELESTE AGOSTINA' },
    //   { dni: '39791605', lastname: 'PEREYRA VEGA', name: ' SABRINA AGOSTINA' },
    //   { dni: '30634661', lastname: 'TRIAS CARRATU', name: ' JULIETA ERICA' },
    //   { dni: '37832672', lastname: 'MONTIVEROS', name: ' MARIA LAURA' },
    //   { dni: '43423361', lastname: 'SUAREZ ROCO', name: ' FRANCISCO NAHUEL' },
    //   { dni: '35734704', lastname: 'MAMONE', name: ' MARIA BELEN' },
    //   { dni: '44674906', lastname: 'ANDRADA OCHOA', name: ' YAMILA VICTORIA' },
    //   { dni: '38591419', lastname: 'DIAPOL', name: ' NICOLAS ENRIQUE' },
    //   {
    //     dni: '34920811',
    //     lastname: 'LEIRIA ILLANES',
    //     name: ' MARIANELA ROMINA',
    //   },
    //   { dni: '39996046', lastname: 'FALCÓN', name: ' NAHIR AYMARA' },
    //   { dni: '42207113', lastname: 'AGUIRRE', name: ' EVELIN YAMILA' },
    //   { dni: '29358282', lastname: 'GONZALEZ', name: ' CAROLINA NOEMI' },
    //   { dni: '39524790', lastname: 'CUELLO', name: ' YAMILA MATILDE' },
    //   { dni: '35849496', lastname: 'LOBOS', name: ' SABRINA' },
    //   { dni: '33438352', lastname: 'DIAZ', name: ' CINTIA TAMARA' },
    //   { dni: '38592260', lastname: 'CARMONA DIPP', name: ' RODRIGO ALEJANDRO' },
    //   { dni: '44317109', lastname: 'REUS SANCHEZ', name: ' GONZALO GABRIEL' },
    //   { dni: '44730794', lastname: 'DIAZ RIVEROS', name: ' VALENTINA BELEN' },
    //   { dni: '40779755', lastname: 'URBANO ZALAZAR', name: ' SARA MARLENE' },
    //   { dni: '38461534', lastname: 'GARCIA', name: ' MARIA DEL CARMEN' },
    //   { dni: '43838240', lastname: 'SUAREZ GARCIA', name: ' CAMILA NATIVIDAD' },
    //   { dni: '36033585', lastname: 'MATAMORA SASTRE', name: ' MARIA SOLEDAD' },
    //   { dni: '40995741', lastname: 'JUAREZ', name: ' FLORENCIA BEATRIZ' },
    //   { dni: '40591532', lastname: 'DI CARLO', name: ' ANABELA ABIGAIL' },
    //   { dni: '41054392', lastname: 'CABANAY ORTIZ', name: ' MARCELA FERNANDA' },
    //   {
    //     dni: '43953131',
    //     lastname: 'MARTÍN GALDEANO',
    //     name: ' MELINA FLORENCIA',
    //   },
    //   { dni: '36250066', lastname: 'MALDONADO', name: ' MARÍA VALERIA' },
    //   { dni: '42711704', lastname: 'GONZALEZ GARRIDO', name: ' MICAELA ROSA' },
    //   { dni: '41598619', lastname: 'BARRIONUEVO DIAZ', name: ' ARAMIS URIEL' },
    //   { dni: '42452452', lastname: 'MARTIN GOMEZ', name: ' ROCIO BELEN' },
    //   { dni: '40779730', lastname: 'OCHOA', name: ' YAMILA BELEN' },
    //   { dni: '32807796', lastname: 'FLORES', name: ' NOELIA ELIZABET' },
    //   { dni: '39525596', lastname: 'ESPEJO', name: ' MICAELA FERNANDA' },
    //   {
    //     dni: '36864733',
    //     lastname: 'VELAZQUEZ TOLOMEO',
    //     name: ' MARÍA LUCIANA',
    //   },
    //   { dni: '41468435', lastname: 'REINOSO GARCIA', name: ' MARCIA AISHA' },
    //   { dni: '32454499', lastname: 'DIAZ CAÑADA', name: ' CECILIA VANESA' },
    //   { dni: '41701167', lastname: 'MERCADO', name: ' TERESA GUADALUPE' },
    //   { dni: '38461921', lastname: 'CASANGA DEGUER', name: ' VERONICA EMILIA' },
    //   { dni: '42516802', lastname: 'NUÑEZ', name: ' ROCIO NILDA' },
    //   { dni: '42712281', lastname: 'RIVEROS', name: ' GISELA MAGALI' },
    //   { dni: '34243131', lastname: 'CACERES', name: ' MARIANELA ANABEL' },
    //   { dni: '36031954', lastname: 'ORO', name: ' EVELIN NATALIA' },
    //   { dni: '42250327', lastname: 'DIAZ CANTOS', name: ' TAMARA MARIBEL' },
    //   { dni: '26288124', lastname: 'MIRANDA', name: ' VERONICA LORENA' },
    //   { dni: '43340387', lastname: 'LUJAN', name: ' JULIETA GISEL' },
    //   { dni: '41598205', lastname: 'VENTURINI GODOY', name: ' LEANDRO JULIAN' },
    //   { dni: '35508119', lastname: 'ESPEJO MUÑOZ', name: ' ARACELI PAULA' },
    //   { dni: '41909471', lastname: 'ZARATE', name: ' RITA ANGÉLICA' },
    //   { dni: '31379229', lastname: 'MONTAÑO MOYANO', name: ' HILDA MARIANELA' },
    //   { dni: '35923084', lastname: 'AUBONE VALVERDE', name: ' RODRIGO' },
    //   { dni: '38217883', lastname: 'MOLINA', name: ' FRANCO EMANUEL' },
    //   {
    //     dni: '38216770',
    //     lastname: 'FARIAS GUTIERREZ',
    //     name: ' SUSANA ELIZABET',
    //   },
    //   { dni: '35508857', lastname: 'GUTIERREZ MOLINA', name: ' IVANA ANABEL' },
    //   {
    //     dni: '40711655',
    //     lastname: 'ECHEGARAY ESTEBAN',
    //     name: ' SOFIA MACARENA',
    //   },
    //   { dni: '44061851', lastname: 'MUÑOZ AMATA', name: ' ANTONELLA' },
    //   { dni: '38123870', lastname: 'LEGUIZAMÓN', name: ' SOLANA' },
    //   { dni: '44127709', lastname: 'GUALLAMA', name: ' ROMINA ANABEL' },
    //   { dni: '43123173', lastname: 'PAEZ', name: ' MARIANA DEL VALLE' },
    //   { dni: '41776396', lastname: 'ROMERO CHENA', name: ' ANALIA' },
    //   { dni: '34696497', lastname: 'BARILARI PLANA', name: ' MARIA CELESTE' },
    //   { dni: '44018444', lastname: 'VERON PASTEN', name: ' DAYANA MICAELA' },
    //   { dni: '37647233', lastname: 'RUIZ ESTEBES', name: ' MELISA GISEL' },
    //   {
    //     dni: '34920350',
    //     lastname: 'GOMEZ SANCHEZ',
    //     name: ' NATALIA ELIZABETH',
    //   },
    //   { dni: '31323990', lastname: 'MARTIN', name: ' ELIANA GISELA' },
    //   { dni: '41909531', lastname: 'ORTIZ HEREDIA', name: ' ROCIO MARICEL' },
    //   { dni: '38460887', lastname: 'BRIZUELA TELLO', name: ' ERICA LEONELA' },
    //   { dni: '44127421', lastname: 'SANCHEZ', name: ' ABRIL NICOLE' },
    //   {
    //     dni: '43690081',
    //     lastname: 'ALVAREZ- VILLAFAÑE',
    //     name: ' ANDREA NOELIA',
    //   },
    //   { dni: '33289483', lastname: 'MOLINA', name: ' ANABELA DE JESÚS' },
    //   { dni: '43555741', lastname: 'FONSECA', name: ' LUDMILA YAEL' },
    //   { dni: '43952484', lastname: 'QUIROGA LEYES', name: ' PAULA ANABELA' },
    //   {
    //     dni: '42516799',
    //     lastname: 'JORQUERA AROSTICA',
    //     name: ' MARIA MILAGROS',
    //   },
    //   {
    //     dni: '37297696',
    //     lastname: 'GONZALES IRAZOQUE',
    //     name: ' DANIELA CELESTE',
    //   },
    //   {
    //     dni: '40939438',
    //     lastname: 'PAREDES CARMONA',
    //     name: ' GABRIELA DEL MILAGRO',
    //   },
    //   { dni: '37646527', lastname: 'BAEZ', name: ' PATRICIA ALEJANDRA' },
    //   { dni: '39183372', lastname: 'QUERO GONZALEZ', name: ' CINTHIA DAYANA' },
    //   { dni: '35511303', lastname: 'HERRERA', name: ' MAIRA NADIR' },
    //   { dni: '44916201', lastname: 'ELIZONDO', name: ' MARCOS ANDRÉS' },
    //   { dni: '35736887', lastname: 'FERRERO FLORES', name: ' DAIANA LILIANA' },
    //   {
    //     dni: '42287610',
    //     lastname: 'SALINAS TAPIAS',
    //     name: ' GUADALUPE MICAELA',
    //   },
    //   { dni: '32723597', lastname: 'BRIZUELA FARIAS', name: ' FLAVIA PAMELA' },
    //   { dni: '34698182', lastname: 'RIVERO ROBLEDO', name: ' JESSICA PAMELA' },
    //   { dni: '41468420', lastname: 'MARTIN', name: ' MICAELA JOHANA' },
    //   {
    //     dni: '32353207',
    //     lastname: 'ORTEGA HERRERA',
    //     name: ' EUNICE ELIZABETH',
    //   },
    //   { dni: '35049463', lastname: 'MUÑOZ PALACIO', name: ' NADIA BETSABE' },
    //   { dni: '39007463', lastname: 'PAEZ', name: ' JONATAN AITOR' },
    //   { dni: '42852852', lastname: 'CORREA PASCUAL', name: ' DANIELA BELÉN' },
    //   { dni: '42163161', lastname: 'CASTRO AGÜERO', name: ' CANDELA ANALÍA' },
    //   { dni: '38078667', lastname: 'MATURANO', name: ' MARIA BELÉN' },
    //   { dni: '38074758', lastname: 'ROJAS', name: ' ALDANA MAGALI' },
    //   {
    //     dni: '35849605',
    //     lastname: 'BONILLA ABALLAY',
    //     name: ' ROMINA ELIZABETH',
    //   },
    //   { dni: '26287917', lastname: 'GARAY CUELI', name: ' CECILIA ALEJANDRA' },
    //   { dni: '44403123', lastname: 'RUARTE SARMIENTO', name: ' PAULA LUCIANA' },
    //   { dni: '41468056', lastname: 'RIOS ARTAZA', name: ' YESICA ROMINA' },
    //   { dni: '39010846', lastname: 'MOLINA OLIVARES', name: ' RICARDO' },
    //   { dni: '44249721', lastname: 'ALVAREZ MANZINI', name: ' MARIA AYELÉN' },
    //   { dni: '42373496', lastname: 'BERNHARDT', name: ' CYNTHIA SOLANGE' },
    //   { dni: '39376671', lastname: 'CARRIZO', name: ' FLORENCIA JOSEFINA' },
    //   {
    //     dni: '39955231',
    //     lastname: 'AVELLANEDA GARCIA',
    //     name: ' RENZO EZEQUIEL',
    //   },
    //   { dni: '40711818', lastname: 'CUELLO OVIEDO', name: ' GEMA FERNANDA' },
    //   { dni: '35922768', lastname: 'GUEVARA AGUDO', name: ' EVELYN ANYELEN' },
    //   { dni: '32095325', lastname: 'TELLO', name: ' ANGELICA NOEMI' },
    //   { dni: '43556409', lastname: 'STOPPA MONTIGEL', name: ' ANA MARIBEL' },
    //   {
    //     dni: '36253794',
    //     lastname: 'BUENAMIAZON FERNANDEZ',
    //     name: ' FLORENCIA AGUSTINA',
    //   },
    //   { dni: '39008192', lastname: 'FLORES', name: ' LUCIANA DEL CARMEN' },
    //   { dni: '31888096', lastname: 'VIDELA', name: ' CRISTINA BELÉN' },
    //   { dni: '39182522', lastname: 'CARRIZO', name: ' SILVIA DEL VALLE' },
    //   { dni: '29709894', lastname: 'PUEBLA MACIAS', name: ' ROMINA EDITH' },
    //   { dni: '34245052', lastname: 'PUEBLA MACIAS', name: ' GISELLE MIRNA' },
    //   { dni: '38074980', lastname: 'GUERRERO DIAZ', name: ' PALOMA ANABEL' },
    //   { dni: '39653255', lastname: 'AMOR SCARPITTA', name: ' JESICA BELEN' },
    //   { dni: '40534628', lastname: 'BAUTISTA', name: ' MARIANO FRANCISCO' },
    //   { dni: '35850835', lastname: 'PEREA', name: ' MACARENA' },
    //   {
    //     dni: '39956077',
    //     lastname: 'FLORES GOTTSCHLICH',
    //     name: ' SEBASTIAN GABRIEL',
    //   },
    //   { dni: '44907337', lastname: 'ROCARO VENERDINI', name: ' RAFAEL' },
    //   { dni: '39652850', lastname: 'OLIVER', name: ' DIEGO DANIEL' },
    //   {
    //     dni: '35923833',
    //     lastname: 'MATURANO  ARDILES',
    //     name: ' MERCEDES  JULIETA',
    //   },
    //   { dni: '34916204', lastname: 'PLAZA OCAMPO', name: ' ANA MAGALI' },
    //   { dni: '36033193', lastname: 'VERA PAEZ', name: ' MARIA VIRGINIA' },
    //   { dni: '42187988', lastname: 'FERNANADEZ', name: ' JESICA NOEMI' },
    //   { dni: '39182456', lastname: 'PÉREZ HERNÁNDEZ', name: ' PAULA VALERIA' },
    //   { dni: '35507299', lastname: 'MENENDEZ ZAMORA', name: ' PRISCILA NEREA' },
    //   { dni: '42917503', lastname: 'HERRERA', name: ' KAREN DANIELA' },
    //   { dni: '34860131', lastname: 'CORNEJO-VILLEGAS', name: ' ERIKA BEATRIZ' },
    //   {
    //     dni: '39995285',
    //     lastname: 'ROMERO MENENDEZ',
    //     name: ' ALEJANDRA VANESSA',
    //   },
    //   { dni: '32510503', lastname: 'PAEZ', name: ' ELBA NATALIA' },
    //   {
    //     dni: '32353250',
    //     lastname: 'QUIROGA ALVAREZ',
    //     name: ' MARILIN ELIZABET',
    //   },
    //   {
    //     dni: '43688802',
    //     lastname: 'GARCIA CASTRILLON FERRO',
    //     name: ' SOL AGOSTINA',
    //   },
    //   { dni: '44018892', lastname: 'CORALLO', name: ' EMILCE GABRIELA' },
    //   { dni: '33743462', lastname: 'PINTO VARAS', name: ' CINTIA NATALIA' },
    //   { dni: '39651184', lastname: 'RODRIGUEZ', name: ' JOHANA JIMENA' },
    //   { dni: '35507277', lastname: 'POBLETE', name: ' MARCELA ALEJANDRA' },
    //   { dni: '38464042', lastname: 'PEREZ-FIGUEROA', name: ' LAYLA MARIBEL' },
    //   { dni: '43156730', lastname: 'GUIÑAZU ROSALES', name: ' EDUARDO NAHUEL' },
    //   { dni: '39650909', lastname: 'VILA ROMERO', name: ' BIANCA LUCIANA' },
    //   { dni: '34100785', lastname: 'RODRÍGUEZ', name: ' VALERIA JOHANA' },
    //   { dni: '33289349', lastname: 'CHAVEZ', name: ' LEONELA GISELLA' },
    //   { dni: '41157168', lastname: 'CABRERA', name: ' PAULA ALEJANDRA' },
    //   { dni: '43943820', lastname: 'DIAZ', name: ' CANDELA' },
    //   { dni: '44126922', lastname: 'ORELLANO', name: ' ROCIO' },
    //   { dni: '43690114', lastname: 'MORENO', name: ' ERICA YAEL' },
    //   { dni: '42633076', lastname: 'GONZALEZ SANCHEZ', name: ' JULIETA' },
    //   { dni: '36033724', lastname: 'ARANDA PERALTA', name: ' MARIELA BEATRIZ' },
    //   { dni: '43221070', lastname: 'MERCADO CORREA', name: ' AMPARO BELÉN' },
    //   { dni: '46180532', lastname: 'MARINERO', name: ' MARIA VICTORIA' },
    //   { dni: '44634987', lastname: 'RIOS', name: ' MARTINA' },
    //   { dni: '33438399', lastname: 'MARCHANTT', name: ' JESUS ROLANDO' },
    //   { dni: '43556557', lastname: 'MANRIQUE COLOMER', name: ' XIMENA MAITE' },
    //   { dni: '24836505', lastname: 'DIAZ', name: ' LORENA DEL CARMEN' },
    //   {
    //     dni: '44634649',
    //     lastname: 'GARCIA RODRIGUEZ',
    //     name: ' CELINA DANIELA',
    //   },
    //   { dni: '28243478', lastname: 'PERALTA', name: ' FEDERICO OMAR' },
    //   { dni: '26878719', lastname: 'BALMACEDA', name: ' ELINA DANIELA' },
    //   { dni: '35822232', lastname: 'OLMO GÓMEZ', name: ' MELISA BELÉN' },
    //   { dni: '29992876', lastname: 'VIEYRA', name: ' CLAUDIA DANIELA' },
    //   { dni: '41641064', lastname: 'PAEZ', name: ' MARIANO' },
    //   { dni: '39131207', lastname: 'TEJADA', name: ' JONATAN' },
    //   { dni: '43156807', lastname: 'STOCO MUÑOZ', name: ' LAURA TIZIANA' },
    //   { dni: '44634390', lastname: 'FLORES', name: ' CLIDE PATRICIA MABEL' },
    //   { dni: '30835831', lastname: 'PAEZ VILLALOBOS', name: ' ANDREA MARISA' },
    //   { dni: '35849421', lastname: 'SILVA', name: ' LUCIANA' },
    //   { dni: '35848326', lastname: 'ONTIVERO', name: ' ELIANA MELISA' },
    //   {
    //     dni: '31714574',
    //     lastname: 'ORTIZ SANCHO',
    //     name: ' ZVJOHANA MARGARITA',
    //   },
    //   { dni: '33289319', lastname: 'ZÁRATE', name: ' ROMINA ANDREA' },
    //   { dni: '35505572', lastname: 'ESQUIVEL', name: ' MAIRA BEATRIZ' },
    //   { dni: '37832836', lastname: 'MERLO', name: ' DANIELA' },
    //   { dni: '35849441', lastname: 'RETA DIAZ', name: ' KAREN XENIA' },
    //   { dni: '43642880', lastname: 'CABELLO', name: ' LUCIA ESTHER' },
    //   { dni: '34417379', lastname: 'SALAS', name: ' JORGE WASHINGTON' },
    //   { dni: '43340110', lastname: 'QUINTERO', name: ' SOFIA' },
    //   { dni: '31382585', lastname: 'ELIZONDO', name: ' BETIANA JAQUELINA' },
    //   { dni: '27916612', lastname: 'CORTEZ', name: ' ANGELICA ANTONIA' },
    //   { dni: '34916127', lastname: 'AVILA QUIROGA', name: ' MARIA GIMENA' },
    //   { dni: '41054292', lastname: 'ONTIVERO', name: ' LOURDES' },
    //   { dni: '40341051', lastname: 'NARVAEZ', name: ' AYELEN ANAHI' },
    //   { dni: '31129865', lastname: 'VEGA', name: ' MARIA NOELIA' },
    //   { dni: '30688230', lastname: 'PEÑA', name: ' PATRICIA ELIDA' },
    //   { dni: '30563496', lastname: 'ONTIVEROS', name: ' NATALIA  MERCEDES' },
    //   {
    //     dni: '38076806',
    //     lastname: 'ACIAR ORELLANO',
    //     name: ' DANIEL ALEJANDRO',
    //   },
    //   { dni: '39995758', lastname: 'MONTORO TORRES', name: ' JULIAN ENRIQUE' },
    //   { dni: '41468330', lastname: 'YACANTE MUÑOZ', name: ' FABRIZIO MIGUEL' },
    //   {
    //     dni: '43641740',
    //     lastname: 'NIETO AMAYA',
    //     name: ' VALENTINA DEL VALLE',
    //   },
    //   { dni: '43688737', lastname: 'VIDELA', name: ' VICTORIA ELIZABET' },
    //   { dni: '43489552', lastname: 'RAMIREZ', name: ' YASMIN YANEL' },
    //   { dni: '32314486', lastname: 'VERGAR CORREA', name: ' MARA LEILA' },
    //   { dni: '38595250', lastname: 'SILVA', name: ' MELANI AYELEN' },
    //   { dni: '39525712', lastname: 'GIL', name: ' MARA DELVALLE' },
    //   {
    //     dni: '39790911',
    //     lastname: 'BUENO CARRASCOZA',
    //     name: ' MARÍA FLORENCIA',
    //   },
    //   { dni: '37925276', lastname: 'ZEPEDA', name: ' ROMINA LEONOR' },
    //   { dni: '39792457', lastname: 'GONZALEZ COSTA', name: ' MARIA AGUSTINA' },
    //   { dni: '37833117', lastname: 'RODRIGUEZ', name: ' ILIANA MABEL' },
    //   { dni: '39009447', lastname: 'TORRES', name: ' DARIO ALEJANDRO' },
    //   { dni: '40728028', lastname: 'ROJAS RODRIGUEZ', name: ' RUTH YAMILA' },
    //   { dni: '37834006', lastname: 'PEREZ', name: ' ABIGAIL BELEN' },
    //   { dni: '24879210', lastname: 'SAEZ PARADA', name: ' ELIANA ENRIQUETA' },
    //   { dni: '44633661', lastname: 'MORAN ABALLAY', name: ' ORIANA NAHIR' },
    //   { dni: '31005162', lastname: 'PUEBLA MACIAS', name: ' GERARDO DANIEL' },
    //   {
    //     dni: '32374968',
    //     lastname: 'BARROSO AVILA',
    //     name: ' CECILIA ALEJANDRA',
    //   },
    //   {
    //     dni: '38594030',
    //     lastname: 'MARTINEZ',
    //     name: ' HILDA VIVIANA MARTINEZ',
    //   },
    //   {
    //     dni: '38218294',
    //     lastname: 'CONTRERAS TIRADO',
    //     name: ' FLAVIA MARCELA',
    //   },
    //   { dni: '37742906', lastname: 'SARMIENTO VAZQUEZ', name: ' SERGIO ARIEL' },
    //   { dni: '42853351', lastname: 'MUÑOZ DURAN', name: ' EVELYN MICAELA' },
    //   { dni: '40469662', lastname: 'MONLA', name: ' NADIA SOLEDAD' },
    //   { dni: '37495099', lastname: 'BUTEL', name: ' ANTONELLA' },
    //   { dni: '41531801', lastname: 'ESQUIVEL', name: ' ARIEL MIGUEL' },
    //   { dni: '42805073', lastname: 'MUÑOZ DIAZ', name: ' CANDELA AGOSTINA' },
    //   { dni: '41054985', lastname: 'LAGOS', name: ' MELANIE ABIGAIL' },
    //   { dni: '42762542', lastname: 'DE LIMA', name: ' YONATAN ORLANDO' },
    //   { dni: '43642106', lastname: 'ABALLAY LUNA', name: ' MATÍAS EXEQUIEL' },
    //   { dni: '35510155', lastname: 'ORDUÑA GARCES', name: ' NICOLAS AGUSTIN' },
    //   { dni: '28834807', lastname: 'SANCHEZ', name: ' PAMELA GRACIELA' },
    //   { dni: '43838379', lastname: 'SILVAREZ', name: ' MILAGROS MELINA' },
    //   { dni: '38593788', lastname: 'ESPEJO AMARFIL', name: ' EDUARDO NICOLAS' },
    //   { dni: '33321785', lastname: 'GOMEZ', name: ' CARLA' },
    //   { dni: '30891471', lastname: 'AVILA', name: ' YAMILA PAOLA' },
    //   { dni: '35849239', lastname: 'ONTIVERO', name: ' YESICA ROMINA' },
    //   { dni: '44730964', lastname: 'GIMÉNEZ QUIROGA', name: ' CARLOS YOEL' },
    //   { dni: '41830015', lastname: 'CARRIO PALUMBO', name: ' SELENA DANIELA' },
    //   { dni: '34939956', lastname: 'USAIR', name: ' MARIA JOSE' },
    //   { dni: '43340523', lastname: 'SOSA HERNANDEZ', name: ' ANA PAULA' },
    //   { dni: '44019127', lastname: 'SUAREZ GENEM', name: ' FLORENCIA LOURDES' },
    //   { dni: '25135152', lastname: 'RODRIGUEZ', name: ' ANALIA VALERIA' },
    //   { dni: '36252629', lastname: 'NUÑEZ ZOLAZO', name: ' MARIA JULIANA' },
    //   { dni: '29177389', lastname: 'BALMACEDA', name: ' GABRIELA NATALIA' },
    //   { dni: '37647592', lastname: 'GIL-SANCHEZ', name: ' ROMINA' },
    //   { dni: '33709833', lastname: 'PASTRAN', name: ' GRACIELA ROMINA' },
    //   {
    //     dni: '42632909',
    //     lastname: 'SIMONCELLI BOSSIO',
    //     name: ' FABRIZIO DANIEL',
    //   },
    //   { dni: '29098350', lastname: 'CESPED', name: ' MARIA DALINDA' },
    //   { dni: '44915168', lastname: 'OVIEDO', name: ' CELINA XIMENA' },
    //   {
    //     dni: '43488843',
    //     lastname: 'PERONA QUINTEROS',
    //     name: ' FLORENCIA CLARIBEL',
    //   },
    //   {
    //     dni: '35505970',
    //     lastname: 'GARRAMUÑO JUÁREZ',
    //     name: ' DANIELA ANDREA',
    //   },
    //   {
    //     dni: '41221340',
    //     lastname: 'TRONCOSO SERAFINI',
    //     name: ' MARIO EZEQUIEL',
    //   },
    //   {
    //     dni: '36424498',
    //     lastname: 'MARTINEZ COSTA',
    //     name: ' OSVALDO EXEQUIEL',
    //   },
    //   { dni: '43952435', lastname: 'GOMEZ TEJADA', name: ' SOFIA MARIBEL' },
    //   { dni: '42081622', lastname: 'VEDIA MELVILLE', name: ' JULIETA AYLEN' },
    //   { dni: '31400539', lastname: 'LOPEZ', name: ' CRISTIAN FABIAN' },
    //   { dni: '40728699', lastname: 'PAZ', name: ' DAIANA BELEN' },
    //   {
    //     dni: '43733391',
    //     lastname: 'QUIROGA CASERES',
    //     name: ' VALENTINA MILAGROS',
    //   },
    //   {
    //     dni: '43058654',
    //     lastname: 'GONZALEZ - OLIVERA',
    //     name: ' MARÍA LOURDES',
    //   },
    //   { dni: '38076175', lastname: 'LOPEZ CASTRO', name: ' VELIA AYLEN' },
    //   { dni: '29594097', lastname: 'GANGA SORIA', name: ' WILSON RAUL' },
    //   { dni: '43689686', lastname: 'TELLO', name: ' LUDMILA ALDANA' },
    //   { dni: '21592282', lastname: 'ESPINOLA', name: ' CLAUDIA ALEJANDRA EMA' },
    //   { dni: '44317127', lastname: 'OJEDA GARRAMUÑO', name: ' MARIA LUDMILA' },
    //   { dni: '44730190', lastname: 'MARTICORENA', name: ' EVELIN MALENA' },
    //   { dni: '44479197', lastname: 'DELGADO', name: ' JUANA CECILIA' },
    //   { dni: '43642519', lastname: 'HEREDIA', name: ' AGUSTINA BELEN' },
    //   { dni: '44061552', lastname: 'CASTRO AHUMADA', name: ' NICOLE MAGALI' },
    //   {
    //     dni: '43953383',
    //     lastname: 'GELVEZ GUAQUINCHAY',
    //     name: ' ALEJANDRA MICAELA',
    //   },
    //   { dni: '45263443', lastname: 'CASTRO CAMACHO', name: ' LOURDES AYELEN' },
    //   { dni: '31888026', lastname: 'MONTAÑA', name: ' NATALÍ VANESA' },
    //   { dni: '38074502', lastname: 'MORALES DONOSO', name: ' MARIA GIMENA' },
    //   { dni: '44317706', lastname: 'TEJADA', name: ' RAMON NICOLAS' },
    //   { dni: '40779367', lastname: 'MUÑOZ AGUERO', name: ' ROCIO PAMELA' },
    //   { dni: '44018961', lastname: 'SANCHEZ', name: ' AGUSTINA DEL VALLE' },
    //   { dni: '41641108', lastname: 'CASTRO', name: ' SEBASTIAN ALEJO' },
    //   { dni: '39007294', lastname: 'ORTIZ', name: ' MICAELA AYELEN' },
    //   { dni: '44317277', lastname: 'FERNANDEZ', name: ' SANTIAGO JAIR' },
    //   { dni: '39956014', lastname: 'ROMERO', name: ' ROCIO MARISOL' },
    //   { dni: '35850181', lastname: 'DIAZ ALCAYAGA', name: ' FACUNDO HERNAN' },
    //   { dni: '39008689', lastname: 'PEREZ', name: ' JOSE LUIS' },
    //   { dni: '37641009', lastname: 'SÁNCHEZ', name: ' YESICA LUCIA' },
    //   { dni: '32718900', lastname: 'SANCHEZ', name: ' YESICA LUCIA' },
    //   { dni: '35849315', lastname: 'CHAVEZ', name: ' CLAUDIA CAROLINA' },
    //   { dni: '43376391', lastname: 'SEVA CARMONA', name: ' EVELIN ARIANA' },
    //   { dni: '32750601', lastname: 'ALBARRACIN', name: ' VALERIA' },
    //   { dni: '43953287', lastname: 'GIL CHICO', name: ' SAMIRA' },
    //   { dni: '32571451', lastname: 'FLORES PERES', name: ' VICTOR EMMANUEL' },
    //   { dni: '37462118', lastname: 'MOLINELLI', name: ' EUGENIA TAMARA' },
    //   { dni: '39955975', lastname: 'PAEZ BRITO', name: ' GONZALO GABRIEL' },
    //   { dni: '38076810', lastname: 'LOPEZ SALINAS', name: ' JEMINA ESTHER' },
    //   { dni: '39376306', lastname: 'VALVERDE', name: ' MAIRA VANESA' },
    //   { dni: '38590606', lastname: 'PEREZ GIMENEZ', name: ' MACARENA JOANA' },
    //   { dni: '34279777', lastname: 'NARVAEZ', name: ' YAMILA ELIZABETH' },
    //   { dni: '33450234', lastname: 'BURGOA', name: ' ROLANDO CESAR' },
    //   { dni: '42711894', lastname: 'DIAZ BALMACEDA', name: ' NAHUEL' },
    //   { dni: '43340660', lastname: 'GARCIA PALLERO', name: ' ANA LAURA' },
    //   { dni: '44808691', lastname: 'SEGOVIA OLAYA', name: ' GIMENA CAROLINA' },
    //   { dni: '41830445', lastname: 'DELGADO ORTEGA', name: ' CAROLINA SOFÍA' },
    //   { dni: '37646603', lastname: 'TAILLANT', name: ' MARÍA AGOSTINA' },
    //   {
    //     dni: '42712481',
    //     lastname: 'ROLDAN SEGOVIA',
    //     name: ' ANDRES ALEJANDRO',
    //   },
    //   { dni: '31860078', lastname: 'CASTRO ATIENZA', name: ' ANGEL ALEXIS' },
    //   { dni: '38075342', lastname: 'GONZALEZ', name: ' EMILI TAMARA' },
    //   { dni: '41270746', lastname: 'QUIROGA VALDEZ', name: ' ROCIO YULIANA' },
    //   { dni: '30708968', lastname: 'COLOMBO', name: ' MARTIN' },
    //   { dni: '41014128', lastname: 'ALVAREZ', name: ' SABRINA FABIANA' },
    //   { dni: '29098119', lastname: 'FERNÁNDEZ', name: ' YESICA EDITH' },
    //   { dni: '34696757', lastname: 'NAVARRO', name: ' PABLO EXEQUIEL' },
    //   { dni: '43556462', lastname: 'DIAZ VALLEJOS', name: ' DAIANA GISEL' },
    //   { dni: '38460451', lastname: 'RODRIGUEZ', name: ' MELISA GABRIELA' },
    //   { dni: '34969757', lastname: 'NAVARRO', name: ' PABLO' },
    //   { dni: '35735264', lastname: 'BARON', name: ' PAULA EMILSE' },
    //   { dni: '44061385', lastname: 'EJARQUE', name: ' ANA' },
    //   {
    //     dni: '42334790',
    //     lastname: 'AGUILERA AVELLANEDA',
    //     name: ' ROBERTO GABRIEL',
    //   },
    //   { dni: '43555566', lastname: 'CASTRO NARVAEZ', name: ' ANA LUCIA' },
    //   { dni: '30151695', lastname: 'LUCERO', name: ' ZULMA CARINA' },
    //   { dni: '43123129', lastname: 'RIVEROS', name: ' AGOSTINA JUDITH' },
    //   { dni: '40728088', lastname: 'GARAY', name: ' FLORENCIA BELEN' },
    //   { dni: '32454464', lastname: 'CARBAJO', name: ' MARIA DE LOS ANGELES' },
    //   { dni: '44674563', lastname: 'GASCON', name: ' CANDELA' },
    //   { dni: '43764245', lastname: 'POULET PENISSE', name: ' FRANCO ISMAEL' },
    //   { dni: '43340301', lastname: 'ELIZONDO NEIRA', name: ' CAMILA' },
    //   { dni: '44527268', lastname: 'MUÑOZ ELIZONDO', name: ' ALEXIS GERMAN' },
    //   { dni: '34054247', lastname: 'SÁNCHEZ', name: ' JENNIE' },
    //   { dni: '38216883', lastname: 'ALANIZ', name: ' CAMILA AGUSTINA' },
    //   { dni: '31129609', lastname: 'CARDOZO', name: ' FRANCO ARIEL' },
    //   { dni: '44061978', lastname: 'CABALLERO', name: ' GONZALO ARIEL' },
    //   { dni: '35049821', lastname: 'PAZ', name: ' FERNANDA GISELA' },
    //   { dni: '27350830', lastname: 'AGUERO', name: ' MARIA EUGENIA' },
    //   {
    //     dni: '40470038',
    //     lastname: 'IRAZOQUE QUINTERO',
    //     name: ' GABRIELA NOEMÍ',
    //   },
    //   { dni: '42287635', lastname: 'PUEBLA CARMONA', name: ' MARIA EUGENIA' },
    //   { dni: '39954725', lastname: 'GALDEANO ESQUIVEL', name: ' ROCIO ISABEL' },
    //   { dni: '25319433', lastname: 'QUINTEROS', name: ' MARTA CELINA' },
    //   { dni: '37924582', lastname: 'ROMERO', name: ' RODRIGO GERMAN' },
    //   { dni: '31658850', lastname: 'SALINAS', name: ' JORGE GABRIEL' },
    //   { dni: '33321514', lastname: 'ARIZA', name: ' VANESA PAOLA' },
    //   { dni: '35848088', lastname: 'TOBAR ATENCIO', name: ' PAULA JULIETA' },
    //   { dni: '38404370', lastname: 'DELAUDE', name: ' FABIO AGUSTIN' },
    //   { dni: '28218942', lastname: 'BUSTOS SANCHEZ', name: ' YAMILA PENÉLOPE' },
    //   { dni: '37531057', lastname: 'ARAUJO FURLAN', name: ' SERGIO ALBERTO' },
    //   { dni: '42858417', lastname: 'PLAZA', name: ' YAMILA AGUSTINA' },
    //   { dni: '40368515', lastname: 'SALINAS', name: ' ERICA ELIZABET' },
    //   { dni: '41054206', lastname: 'MORAL ROMERO', name: ' MELANI YASMIN' },
    //   { dni: '41270894', lastname: 'SORIA CORIA', name: ' MARIA ELENA' },
    //   { dni: '33625416', lastname: 'BECERRA', name: ' CARLOS' },
    //   { dni: '38461106', lastname: 'HERAS CASTRO', name: ' MARIANA TERESITA' },
    //   { dni: '37641120', lastname: 'NIEVAS AGUERO', name: ' ANDREA YAMILA' },
    //   { dni: '39956105', lastname: 'IBAÑEZ NOGUERA', name: ' KARLA ROCIO' },
    //   { dni: '36864662', lastname: 'ARGÜELLO', name: ' CECILIA ENRIQUETA' },
    //   { dni: '42006146', lastname: 'YAÑEZ LOPEZ', name: ' LUCIANA' },
    //   { dni: '43689753', lastname: 'GONZALEZ GONZALEZ', name: ' ELIAS JOEL' },
    //   { dni: '27984579', lastname: 'AGUIRRE', name: ' NATALIA YOLANDA' },
    //   { dni: '35208984', lastname: 'QUILPATAY GARAY', name: ' CARLA YANINA' },
    //   { dni: '31979608', lastname: 'PONCE DIAZ', name: ' PATRICIA DEL VALLE' },
    //   {
    //     dni: '37925130',
    //     lastname: 'SAAVEDRA CASTRO',
    //     name: ' FLORENCIA ALDANA',
    //   },
    //   { dni: '31871449', lastname: 'TOBAR ATENCIO', name: ' ROMINA BELEN' },
    //   { dni: '33234060', lastname: 'VERAZAY', name: ' ELIANA PAMELA' },
    //   { dni: '31044192', lastname: 'VIDELA AMAYA', name: ' CARMEN ROSARIO' },
    //   {
    //     dni: '42516516',
    //     lastname: 'VALVERDE CASTRO',
    //     name: ' SEBASTIÁN NÉSTOR',
    //   },
    //   { dni: '35736049', lastname: 'ALONSO ROMERO', name: ' MARIA FLORENCIA' },
    //   { dni: '38078654', lastname: 'OCHOA', name: ' GONZALO GASTÓN' },
    //   { dni: '42287530', lastname: 'VERA ZEVALLOS', name: ' GEMA MARÍA LUZ' },
    //   { dni: '33826092', lastname: 'LOPEZ CANO', name: ' MARIA LUZ' },
    //   {
    //     dni: '43690032',
    //     lastname: 'MALDONADO GARCÍA',
    //     name: ' GUADALUPE MARIA',
    //   },
    //   { dni: '42334772', lastname: 'ROMERO', name: ' FATIMA GUADALUPE' },
    //   { dni: '40728048', lastname: 'SARRUFF', name: ' SHEILA NAHIR' },
    //   { dni: '44439443', lastname: 'CASTRO', name: ' YANIRA BELEN' },
    //   { dni: '35850343', lastname: 'BERÓN', name: ' CINTIA ALEJANDRA' },
    //   { dni: '31870978', lastname: 'DIAZ', name: ' AMILCAR CLAUS' },
    //   { dni: '30634283', lastname: 'CARBAJAL', name: ' ELISA' },
    //   { dni: '35091199', lastname: 'DI CARLO', name: ' MELISA CRISTINA' },
    //   { dni: '41809149', lastname: 'MALLEA RIVERO', name: ' LEANDRO ABEL' },
    //   { dni: '39995955', lastname: 'SAAVEDRA', name: ' LOURDE CYNTIA JIMENA' },
    //   { dni: '43689400', lastname: 'JUAN RIVEROS', name: ' ERIKA ESTEFANIA' },
    //   { dni: '32807410', lastname: 'AGUADO', name: ' JESICA JOHANA' },
    //   { dni: '42821059', lastname: 'TORREZ BARIN', name: ' MELINA NAOMI' },
    //   { dni: '38595151', lastname: 'PERETO PERALTA', name: ' MACARENA' },
    //   { dni: '39224533', lastname: 'RIVAS', name: ' MARIELA ITATI' },
    //   {
    //     dni: '39647658',
    //     lastname: 'NOGUERA   QUIROGA',
    //     name: ' MARIA FLORENCIA',
    //   },
    //   { dni: '35938104', lastname: 'PLAZA', name: ' LEILA MARIBEL' },
    //   { dni: '40367702', lastname: 'FLORES MOYANO', name: ' BRAIAN' },
    //   { dni: '44634991', lastname: 'ESPINOSA', name: ' SAYEN  ITATI' },
    //   {
    //     dni: '43156869',
    //     lastname: 'MARTINEZ MONTAÑA',
    //     name: ' SOFIA MILAGROS',
    //   },
    //   { dni: '42444449', lastname: 'VEGA', name: ' VICTORIA ALEJANDRA' },
    //   { dni: '40939447', lastname: 'MERELES', name: ' FLORENCIA JANET' },
    //   { dni: '39182774', lastname: 'VALDEZ PEREZ', name: ' AGUSTIN ENRIQUE' },
    //   { dni: '42712231', lastname: 'ROSALEZ', name: ' MARIANELA' },
    //   { dni: '28744788', lastname: 'MOLINA', name: ' ESTELA VERONICA' },
    //   { dni: '42334323', lastname: 'NAVARRO', name: ' FLORENCIA BARBARA NAIR' },
    //   { dni: '36250230', lastname: 'SIERRA', name: ' ELIANA VANINA' },
    //   { dni: '33429688', lastname: 'SEGURA CORTEZ', name: ' CESAR ALEJANDRO' },
    //   { dni: '34329282', lastname: 'BUSTOS', name: ' MARIA ROSA' },
    //   { dni: '41054880', lastname: 'MILANA', name: ' SANTIAGO IGNACIO' },
    //   { dni: '44633909', lastname: 'SANCHEZ SANCHEZ', name: ' MARIA CELESTE' },
    //   { dni: '35507520', lastname: 'FERREIRA', name: ' CARLOS ALFREDO' },
    //   { dni: '46726061', lastname: 'IBAZETA', name: ' ANTONELLA MAGALÍ' },
    //   { dni: '41468593', lastname: 'RODRIGUEZ', name: ' JIMENA BEATRIZ' },
    //   {
    //     dni: '44991019',
    //     lastname: 'VERA-RODRIGUEZ',
    //     name: ' MARIA CLARA SOLEDAD',
    //   },
    //   { dni: '43220808', lastname: 'GENINI MARECA', name: ' MATIAS AGUSTÍN' },
    //   { dni: '41814034', lastname: 'CASTRO', name: ' MILAGROS DEL ROSARIO' },
    //   { dni: '43642633', lastname: 'GÁNDARA', name: ' PAULA JULIETA' },
    //   { dni: '43641746', lastname: 'AMAYA', name: ' NATASHA NICOLE' },
    //   {
    //     dni: '24972471',
    //     lastname: 'LEIVA GONZALEZ',
    //     name: ' JOSEFA DEL PILAR',
    //   },
    //   { dni: '39008194', lastname: 'AZCURRA', name: ' MARIA BELEN' },
    //   { dni: '44061832', lastname: 'FLORES', name: ' FRANCO DAVID' },
    //   { dni: '38460647', lastname: 'ESCUDERO', name: ' MAXIMILIANO GABRIEL' },
    //   { dni: '42990475', lastname: 'TEJADA', name: ' AILIN SOFIA' },
    //   { dni: '41468224', lastname: 'DOMINGUEZ MASI', name: ' ANTONELLA LUZ' },
    //   { dni: '44916543', lastname: 'ROJAS', name: ' MELANI YULIANA' },
    //   { dni: '41909143', lastname: 'SANCHEZ TORES', name: ' GIMENA VICTORIA' },
    //   { dni: '38462019', lastname: 'BERRIDO', name: ' LUCIANA' },
    //   { dni: '42249725', lastname: 'AGUILERA CUELLO', name: ' MARIA LUCIANA' },
    //   { dni: '36033625', lastname: 'SOSA', name: ' IVANA GISEL' },
    //   {
    //     dni: '42005998',
    //     lastname: 'FERNÁNDEZ TAPIA',
    //     name: ' MARIA DEL ROSARIO',
    //   },
    //   {
    //     dni: '41830238',
    //     lastname: 'CARRACEDO CHAVEZ',
    //     name: ' SOFIA CARRACEDO',
    //   },
    //   { dni: '39376712', lastname: 'ESPEJO', name: ' CATERINA' },
    //   { dni: '40264827', lastname: 'PEREZ', name: ' ROCIO IVON' },
    //   { dni: '42853148', lastname: 'BONDANZA MEDINA', name: ' MARIA LURDES' },
    //   {
    //     dni: '44432087',
    //     lastname: 'ESPINOSA LEPEZ',
    //     name: ' LUISINA DEL ROSARIO',
    //   },
    //   {
    //     dni: '43555648',
    //     lastname: 'HERRERA ESQUIVEL',
    //     name: ' VALENTINA CAMILA',
    //   },
    //   { dni: '35850171', lastname: 'SANTANA', name: ' BETIANA VERÓNICA' },
    //   { dni: '36254384', lastname: 'CHAVES GALLO', name: ' RINA INES' },
    //   { dni: '45378875', lastname: 'VERA MURA', name: ' LUCIANO NICOLAS' },
    //   {
    //     dni: '41468163',
    //     lastname: 'TEJADA CORTEZ',
    //     name: ' FERNANDA MARIANELA',
    //   },
    //   {
    //     dni: '43763381',
    //     lastname: 'MORENO FERNÁNDEZ',
    //     name: ' MARÍA FLORENCIA',
    //   },
    //   { dni: '35736289', lastname: 'IVACACHE', name: ' ANA YANEL' },
    //   { dni: '38460104', lastname: 'FLORES', name: ' FERNANDO ARIEL' },
    //   {
    //     dni: '38592061',
    //     lastname: 'AGUIRRE FERREIRA',
    //     name: ' ALEJANDRO EZEQUIEL',
    //   },
    //   { dni: '39653241', lastname: 'CILIA', name: ' MARIA' },
    //   { dni: '42805112', lastname: 'ONTIVERO', name: ' ABIGAIL' },
    //   { dni: '38076052', lastname: 'MUÑOZ MONTAÑA', name: ' ALDANA MARIA' },
    //   { dni: '43221167', lastname: 'ABALLAY', name: ' SOFIA LOURDES' },
    //   { dni: '32717329', lastname: 'GARCIA', name: ' ANA CAROLINA' },
    //   { dni: '35208844', lastname: 'ALBAREZ RODRIGUEZ', name: ' ANDREA BELÉN' },
    //   { dni: '36588296', lastname: 'ORO FERNANDEZ', name: ' ELIANA GABRIELA' },
    //   { dni: '44634277', lastname: 'SIERRA ZAPATA', name: ' ALEJO JESUS' },
    //   { dni: '35089365', lastname: 'MUÑOZ', name: ' MARIANA' },
    //   {
    //     dni: '33289741',
    //     lastname: 'HERNANDEZ MARTINEZ',
    //     name: ' UBEN EMILIO ERNESTO',
    //   },
    //   { dni: '31209179', lastname: 'ORTIZ', name: ' PAMELA SABRINA' },
    //   { dni: '44317150', lastname: 'SAAVEDRA MORALES', name: ' LUISINA BELÉN' },
    //   { dni: '41017262', lastname: 'SOSA', name: ' ROXANA LUCIA' },
    //   { dni: '42917884', lastname: 'SABAS', name: ' YESICA CAROL' },
    //   { dni: '43642347', lastname: 'ARREDONDO', name: ' AGUSTINA' },
    //   { dni: '41157136', lastname: 'SIEBERHERRERA', name: ' IRINA' },
    //   { dni: '41468887', lastname: 'ROMERO', name: ' NICOLÁS DANIEL' },
    //   { dni: '35507269', lastname: 'SABAS', name: ' MARIA BELEN' },
    //   { dni: '30402241', lastname: 'FERNANDEZ SALINAS', name: ' IVANA RAQUEL' },
    //   { dni: '41682510', lastname: 'GUZMAN SOSA', name: ' ERICA MICAELA' },
    //   { dni: '32929611', lastname: 'PAEZ', name: ' VALERIA DEL CARMEN' },
    //   { dni: '43556152', lastname: 'AGUERO', name: ' EMILIANO MARTIN' },
    //   {
    //     dni: '36253120',
    //     lastname: 'BARRIONUEVO MARTINEZ',
    //     name: ' ROXANA AYLEN',
    //   },
    //   { dni: '35070701', lastname: 'GOMEZ', name: ' YAMIL SEBASTIAN' },
    //   { dni: '37750914', lastname: 'CASTILLO PARRA', name: ' LEONEL' },
    //   { dni: '35507261', lastname: 'LIZZI', name: ' GISELA LILIANA' },
    //   { dni: '31496894', lastname: 'GUEVARA VEGA', name: ' MONICA GABRIELA' },
    //   { dni: '35857905', lastname: 'BRAVO', name: ' FLAVIA NATALIA' },
    //   {
    //     dni: '44127118',
    //     lastname: 'OLIVERA PERUZZI',
    //     name: ' MARTINA TRINIDAD',
    //   },
    //   { dni: '43642949', lastname: 'OLIVERA', name: ' ROCIO ANALIA' },
    //   {
    //     dni: '44766667',
    //     lastname: 'ATENCIO ACHILLES',
    //     name: ' LUCAS NAZARENO',
    //   },
    //   { dni: '35782631', lastname: 'SOLARES', name: ' ELIANA FLORENCIA' },
    //   { dni: '39183983', lastname: 'TALQUENCA', name: ' TATIANA BELEN' },
    //   { dni: '41814303', lastname: 'RIVFEROS', name: ' MARIA ITATI' },
    //   {
    //     dni: '43280946',
    //     lastname: 'ALCALA VIDELA',
    //     name: ' ARACELI GUADALUPE',
    //   },
    //   {
    //     dni: '27490151',
    //     lastname: 'FLORES MANRIQUE',
    //     name: ' MARINA DEL VALLE',
    //   },
    //   { dni: '37648881', lastname: 'MUÑOZ', name: ' BARBARA MICAELA' },
    //   { dni: '39182913', lastname: 'FRIAS', name: ' JENIFER ROMINA' },
    //   { dni: '28668579', lastname: 'FERNANDEZ', name: ' DAVID DIEGO' },
    //   { dni: '36032742', lastname: 'PEREZ', name: ' FERNANDA M' },
    //   { dni: '28448200', lastname: 'BILBAO', name: ' DANIELA NERINA' },
    //   {
    //     dni: '43952003',
    //     lastname: 'MONTIVERO POBLETE',
    //     name: ' MARIA FERNANDA',
    //   },
    //   { dni: '42452430', lastname: 'ESTEBA', name: ' IVAN ORLANDO' },
    //   { dni: '39792690', lastname: 'MARTINEZ MALLEA', name: ' JULIETA IVON' },
    //   { dni: '42163083', lastname: 'FLORES', name: ' ANA BELÉN' },
    //   { dni: '44062164', lastname: 'LUCERO VERA', name: ' ALDANA AYLEN' },
    //   { dni: '43952586', lastname: 'CORTEZ', name: ' ROCIO' },
    //   { dni: '39652865', lastname: 'ALVAREZ', name: ' MAYRA ABIGAIL' },
    //   { dni: '40592734', lastname: 'PARADA', name: ' MARIA LAURA' },
    //   { dni: '44526529', lastname: 'YACANTE PIZARRO', name: ' MABEL YAMILA' },
    //   { dni: '39011362', lastname: 'MARTIN FERNANDEZ', name: ' LUCIANA' },
    //   { dni: '36032731', lastname: 'BALMACEDA', name: ' FEDERICO GABRIEL' },
    //   { dni: '43763327', lastname: 'ROSELLO MORENO', name: ' ROCIO JORGELINA' },
    //   { dni: '43376753', lastname: 'BARRIONUEVO', name: ' BRISE JASMIN' },
    //   { dni: '38217260', lastname: 'VARAS CARRIZO', name: ' ELIZABETH MILENA' },
    //   { dni: '39652655', lastname: 'SANCHEZ', name: ' TAMARA AYELEN' },
    //   { dni: '42187951', lastname: 'ALMAZAN', name: ' JUAN LAUTARO' },
    //   {
    //     dni: '44316040',
    //     lastname: 'GALLO VILLANUEVA',
    //     name: ' GUADALUPE MARIANA',
    //   },
    //   { dni: '42451604', lastname: 'BENITO REYES', name: ' MARCIA BELÉN' },
    //   { dni: '43157406', lastname: 'PEDRAZA', name: ' VERÓNICA FLORENCIA' },
    //   { dni: '42805941', lastname: 'OZÁN QUILES', name: ' MILAGROS LUDMILA' },
    //   { dni: '37641150', lastname: 'PARATORE', name: ' DAYANA BELEN' },
    //   { dni: '38463002', lastname: 'MERELES', name: ' MARCIA ESTEFANIA' },
    //   {
    //     dni: '39011107',
    //     lastname: 'VILLAFAÑE CHACON',
    //     name: ' HILDA FERNANDA',
    //   },
    //   { dni: '39010726', lastname: 'CASTRO', name: ' YULIANA VALERIA' },
    //   { dni: '37507566', lastname: 'BERNARDELLO', name: ' MAURO JAVIER' },
    //   { dni: '44479131', lastname: 'DI LORENZO SASSU', name: ' GUILLERMINA' },
    //   { dni: '37924027', lastname: 'ARIAS CARRIZO', name: ' ANDREA MARIANA' },
    //   {
    //     dni: '40823817',
    //     lastname: 'LOPEZ ORTIZ',
    //     name: ' YAMILA DEL VALLE JESUS',
    //   },
    //   { dni: '44665690', lastname: 'ROJOS CASTRO', name: ' TANIA MAGALI' },
    //   { dni: '29264277', lastname: 'PALACIO', name: ' DANIELA ELIANA' },
    //   { dni: '33236792', lastname: 'PINTOR GONZALEZ', name: ' ANALIA CECILIA' },
    //   { dni: '24234089', lastname: 'RODRIGUEZ', name: ' VALERIA PATRICIA' },
    //   { dni: '44316838', lastname: 'MULET  BUSTAMANTE', name: ' ROSA  MARIA' },
    //   { dni: '27474086', lastname: 'GOMEZ', name: ' JORGE MARCELO' },
    //   {
    //     dni: '39009644',
    //     lastname: 'POBLETE MARINERO',
    //     name: ' EVELIN VICTORIA',
    //   },
    //   { dni: '38460036', lastname: 'GONZALEZ', name: ' DANIELA EVELIN' },
    //   { dni: '44634812', lastname: 'MUROS GÓMEZ', name: ' BRISA CAMILA' },
    //   { dni: '39182716', lastname: 'PATTINI IBIZA', name: ' NOELIA DEL VALLE' },
    //   { dni: '41054677', lastname: 'CAPUTO', name: ' PAULA MARTINA' },
    //   {
    //     dni: '44604686',
    //     lastname: 'SAAVEDRA DE LA VEGA',
    //     name: ' NICOLE DAIANA',
    //   },
    //   { dni: '39008322', lastname: 'MORETA', name: ' KAREN ESTEFANIA' },
    //   { dni: '40728732', lastname: 'CERDA GARCIA', name: ' ANGELES AGOSTINA' },
    //   { dni: '23283416', lastname: 'LUCERO', name: ' GABRIELA ANDREA' },
    //   { dni: '44808664', lastname: 'MAYA SEGURA', name: ' ARACELI VANINA' },
    //   { dni: '41909133', lastname: 'NAVARRO', name: ' NIHUEL' },
    //   { dni: '35735642', lastname: 'SANCHEZ PAREDES', name: ' ANA YAMILA' },
    //   { dni: '43376696', lastname: 'SORIA', name: ' FLORENCIA VALENTINA' },
    //   { dni: '35735959', lastname: 'BARROS', name: ' KAREN  ELINA' },
    //   { dni: '38074800', lastname: 'RIGAZZIO', name: ' ELIANA ELIZABETH' },
    //   {
    //     dni: '30151606',
    //     lastname: 'SANCHEZ PAREDES',
    //     name: ' MARIA ALEJANDRA',
    //   },
    //   { dni: '32095163', lastname: 'HEREDIA', name: ' JONATHAN  EDUARDO' },
    //   { dni: '42081693', lastname: 'ESPEJO', name: ' RAMON ALEXIS' },
    //   { dni: '43555604', lastname: 'MOLINA VALLEJO', name: ' DANIELA' },
    //   { dni: '43763640', lastname: 'ROBLEDO', name: ' ELIANA ANDREA' },
    //   { dni: '44634526', lastname: 'ZAMBRA MARINERO', name: ' CANDELA NOÉ' },
    //   {
    //     dni: '42081919',
    //     lastname: 'RIVERO CARRIZO',
    //     name: ' MALENA VALENTINA',
    //   },
    //   { dni: '44062468', lastname: 'AGUERO PEREZ', name: ' SANTIAGO GABRIEL' },
    //   { dni: '35922427', lastname: 'LEITES JOFRE', name: ' MONICA NOELIA' },
    //   { dni: '41598108', lastname: 'GUEVARA AGUILERA', name: ' KAREN AYELEN' },
    //   { dni: '38464051', lastname: 'CASTRO ALBORNOZ', name: ' TANIA PAOLA' },
    //   { dni: '42081694', lastname: 'ESPEJO', name: ' FRANCO RAMON' },
    //   {
    //     dni: '35850373',
    //     lastname: 'ONTIVEROS DAVILA',
    //     name: ' PAMELA ANYELEN',
    //   },
    //   { dni: '39525102', lastname: 'CARMONA SAMPER', name: ' ANA MARÍA' },
    //   {
    //     dni: '42006337',
    //     lastname: 'MERCADO GUZMAN',
    //     name: ' MILAGROS MICAELA',
    //   },
    //   { dni: '37924863', lastname: 'MONTAÑA DIAZ', name: ' FERNANDA ELIANA' },
    //   {
    //     dni: '44991897',
    //     lastname: 'CARRION GONZALEZ',
    //     name: ' MAXIMILIANO SEBASTIAN',
    //   },
    //   { dni: '38076680', lastname: 'RECABARREN', name: ' MARIA AGOSTINA' },
    //   { dni: '41957705', lastname: 'SANTANA DIAZ', name: ' FACUNDO ULISES' },
    //   { dni: '43952524', lastname: 'TORTOSA', name: ' MICAELA AGOSTINA' },
    //   {
    //     dni: '41014452',
    //     lastname: 'SOLCONTRERAS283@GMAIL.COM',
    //     name: ' MARIA SOL',
    //   },
    //   { dni: '43340547', lastname: 'VILLAFAÑE PAEZ', name: ' GIMENA MAGALI' },
    //   { dni: '39651317', lastname: 'MENDEZ', name: ' GIULIANA DEL VALLE' },
    //   { dni: '38074718', lastname: 'FLORES', name: ' ELIANA' },
    //   { dni: '34698707', lastname: 'GODOY', name: ' JOHANA BELÈN' },
    //   { dni: '33183885', lastname: 'DELGADO', name: ' MAIRA NOELIA' },
    //   { dni: '42805325', lastname: 'RODRIGUEZ', name: ' ALDANA ESTEFANIA' },
    //   {
    //     dni: '43422632',
    //     lastname: 'ANTE GONZALEZ',
    //     name: ' MILAGROS ELIZABETH',
    //   },
    //   { dni: '34916368', lastname: 'DIAZ', name: ' DALMA CELESTE' },
    //   { dni: '38758982', lastname: 'ARENA', name: ' MELISA BELEN' },
    //   { dni: '31689631', lastname: 'GORO', name: ' PATRICIA FLORENCIA' },
    //   { dni: '44432367', lastname: 'PINTO', name: ' MARIA SOLANGE' },
    //   { dni: '36254114', lastname: 'BAZAN MORLAS', name: ' JIMENA ANABEL' },
    //   { dni: '43078172', lastname: 'MARINERO', name: ' RUBÉN DARIO' },
    //   {
    //     dni: '38463899',
    //     lastname: 'ECHENIQUE VILLAREAL',
    //     name: ' ARIEL MAXIMILIANO',
    //   },
    //   { dni: '47238823', lastname: 'MALLA GUERRERO', name: ' CINTHIA BELÉN' },
    //   { dni: '44018289', lastname: 'DIAZ FERNANDEZ', name: ' MARIA CANDELA' },
    //   { dni: '30891495', lastname: 'SIARES', name: ' JORGE PABLO' },
    //   {
    //     dni: '36250653',
    //     lastname: 'ONTIVERO ECHEGARAY',
    //     name: ' TAMARA BELÉN',
    //   },
    //   {
    //     dni: '39182786',
    //     lastname: 'OLIVERA AHUMADA',
    //     name: ' GABRIEL VALENTIN',
    //   },
    //   { dni: '43078744', lastname: 'DIAZ ELIZONDO', name: ' LUCIANO FABRICIO' },
    //   { dni: '32939273', lastname: 'MORENO', name: ' JOANA ELIZABETH' },
    //   { dni: '33110460', lastname: 'RIVEROS', name: ' VICTORIA  DEL  CARMEN' },
    //   { dni: '38945616', lastname: 'PIZARRO FLORES', name: ' SACHA MICAELA' },
    //   {
    //     dni: '41083294',
    //     lastname: 'MEDRANO-JOFRE',
    //     name: ' EMILIANA MACARENA',
    //   },
    //   { dni: '33743461', lastname: 'CORVALAN', name: ' MARIELA ANALIA' },
    //   {
    //     dni: '36423185',
    //     lastname: 'GALLEGOS VILLAVICENCIO',
    //     name: ' VANINA VERONICA',
    //   },
    //   { dni: '40728137', lastname: 'BLANCO VEGA', name: ' GLENDA TAMARA' },
    //   { dni: '37096242', lastname: 'BRIZUELA', name: ' YOHANA SOLEDAD' },
    //   { dni: '42081321', lastname: 'PAEZ', name: ' SOFÍA LUJÁN' },
    //   { dni: '39792574', lastname: 'PINCHEIRA', name: ' AGOSTINA GUADALUPE' },
    //   {
    //     dni: '40591582',
    //     lastname: 'VILLAFAÑE PAEZ',
    //     name: ' FLORENCIA BEATRIZ',
    //   },
    //   { dni: '42853169', lastname: 'CHICO OVIEDO', name: ' MALENA NOELIA' },
    //   { dni: '39954224', lastname: 'OLIVERA STURMA', name: ' ANA PAULA' },
    //   { dni: '42632946', lastname: 'MEDAWAR VILA', name: ' RODOLFO AGUSTIN' },
    //   { dni: '40469507', lastname: 'WIERNES PAZ', name: ' AUGUSTO' },
    //   { dni: '39790797', lastname: 'ABALLAY PEREIRA', name: ' MARIA MICAELA' },
    //   { dni: '43282069', lastname: 'NIETO', name: ' ANA ROSA' },
    //   { dni: '34613049', lastname: 'ELIZONDO', name: ' LILIA DEBORA' },
    //   { dni: '42711558', lastname: 'ROMERO GORDILLO', name: ' MARIA VICTORIA' },
    //   { dni: '39010559', lastname: 'ROMERO', name: ' MICAELA' },
    //   { dni: '37648334', lastname: 'TELLO', name: ' ABIGAIL ISABEL' },
    //   { dni: '29911566', lastname: 'LUCERO', name: ' MARCELO RODOLFO' },
    //   { dni: '33322202', lastname: 'IBAZETA DIAZ', name: ' LORENA PAOLA' },
    //   {
    //     dni: '38593183',
    //     lastname: 'LUPARELO ESCUDERO',
    //     name: ' MELINA ANTONELLA',
    //   },
    //   { dni: '40368396', lastname: 'CORTEZ', name: ' DIEGO ALEJANDRO' },
    //   { dni: '39999277', lastname: 'RIVERA', name: ' FLORENCIA' },
    //   { dni: '35938515', lastname: 'ARACENA VIVAREZ', name: ' GABRIELA JANET' },
    //   { dni: '42712491', lastname: 'OLMOS ORTEGA', name: ' SOFIA AGOSTINA' },
    //   { dni: '34182337', lastname: 'AHUMADA QUIROGA', name: ' DARIO EMMANUEL' },
    //   { dni: '40593358', lastname: 'GENTILI', name: ' JONATHAN HERNÁN' },
    //   { dni: '41645631', lastname: 'RONDON', name: ' MARIA CIELO' },
    //   {
    //     dni: '44061261',
    //     lastname: 'ONTIVEROS MARQUEZ',
    //     name: ' MILENA AGUSTINA',
    //   },
    //   { dni: '37741971', lastname: 'LAGOS', name: ' CLAUDIA MARIELA' },
    //   { dni: '43641725', lastname: 'AHUMADA', name: ' LUCIANA AGUSTINA' },
    //   { dni: '43339961', lastname: 'PALLERO', name: ' KAREN MAGALI' },
    //   { dni: '39300484', lastname: 'MARTINEZ', name: ' STEFANIA SOLEDAD' },
    //   { dni: '39651061', lastname: 'CORTEZ', name: ' YAMILA MICAELA' },
    //   { dni: '43221027', lastname: 'ORO', name: ' M VALENTINA' },
    //   { dni: '30274107', lastname: 'OCHOA', name: ' GUILLERMO AGUSTÍN' },
    //   {
    //     dni: '35023743',
    //     lastname: 'GUAQUINCHAY MORAN',
    //     name: ' ESTRELLA BELEN',
    //   },
    //   { dni: '39955385', lastname: 'SARMIENTO MALLEA', name: ' MARTINA GEMA' },
    //   { dni: '38074570', lastname: 'ORTIZ', name: ' ISABEL MACARENA' },
    //   {
    //     dni: '28646046',
    //     lastname: 'ANDRADA FERNANDEZ',
    //     name: ' NANCY DEL VALLE',
    //   },
    //   { dni: '34887370', lastname: 'ONTIVERO ECHEGARAY', name: ' ROCIO JANET' },
    //   {
    //     dni: '39954472',
    //     lastname: 'TORTOSA BARRIOS',
    //     name: ' CELESTE DEYANIRA',
    //   },
    //   { dni: '35851649', lastname: 'CASTILLO', name: ' VANINA JEANNETTE' },
    //   { dni: '42452213', lastname: 'OVIEDO LUJAN', name: ' STIVEN JASON' },
    //   { dni: '41641829', lastname: 'GARCIA LUCERO', name: ' CARINA DANIELA' },
    //   {
    //     dni: '35850243',
    //     lastname: 'BALMACEDA GISEL',
    //     name: ' BALMACEDA GISEL LILIANA',
    //   },
    //   { dni: '39182711', lastname: 'PUJADO VEGA', name: ' MARIEL EMILSE' },
    //   {
    //     dni: '39424936',
    //     lastname: 'FERNANDEZ OLIVARES',
    //     name: ' ALEXSANDRA ESTEFANÍA',
    //   },
    //   { dni: '39524540', lastname: 'STORNIOLO POLO', name: ' EVELYN' },
    //   { dni: '38591803', lastname: 'ELIZONDO', name: ' ADRIAN RODOLFO' },
    //   { dni: '39995200', lastname: 'PAEZ', name: ' MARIANA GISEL' },
    //   { dni: '24244925', lastname: 'CHIRINO', name: ' GABRIEL SANTOS' },
    //   { dni: '32679832', lastname: 'DIAZ', name: ' MATIAS EMANUEL' },
    //   { dni: '40939384', lastname: 'MAYA SEGURA', name: ' LUCÍA AYELÉN' },
    //   { dni: '39955506', lastname: 'ALMAZAN', name: ' JESUS LISANDRO' },
    //   { dni: '40728040', lastname: 'CASTRO', name: ' LAURA SOLEDAD' },
    //   { dni: '32860285', lastname: 'CATALDO', name: ' PAULA' },
    //   { dni: '39182679', lastname: 'MUÑOZ ALARCON', name: ' BIANCA BELEN' },
    //   { dni: '41270873', lastname: 'CASTRO GUAJARDO', name: ' MICAELA LUJAN' },
    //   {
    //     dni: '42109167',
    //     lastname: 'LARRARTE VIDELA',
    //     name: ' SOLANGE MILAGROS',
    //   },
    //   { dni: '41531659', lastname: 'LIMA', name: ' ANALIA CARLOTA JUANA' },
    //   { dni: '40779760', lastname: 'CORRALLO', name: ' VALERIA ALEJANDRA' },
    //   { dni: '38217935', lastname: 'ARRANZ', name: ' DANIELA  SOLEDAD' },
    //   { dni: '36438263', lastname: 'DIAZ TINEO', name: ' CESAR ATILIO' },
    //   {
    //     dni: '39183625',
    //     lastname: 'CARCAMO',
    //     name: ' TERESITA NORMA GUADALUPE',
    //   },
    //   { dni: '40369065', lastname: 'CABALLERO', name: ' ROCIO AGOSTINA' },
    //   { dni: '37834043', lastname: 'LOPEZ ARGAÑARAZ', name: ' JESICA BELÉN' },
    //   { dni: '28475222', lastname: 'PRIMO', name: ' JOSÉ ANDRÉS BENITO' },
    //   { dni: '39424520', lastname: 'NAVARRO', name: ' KAREN YANEL' },
    //   { dni: '39651378', lastname: 'OLMEDO', name: ' ROMINA JANET' },
    //   {
    //     dni: '41598591',
    //     lastname: 'BARQUIEL TRUJILLANO',
    //     name: ' MILAGRO AGOSTINA',
    //   },
    //   {
    //     dni: '36136582',
    //     lastname: 'OLIVARES ESTEVEZ',
    //     name: ' GISELLE ROXANA',
    //   },
    //   { dni: '38764011', lastname: 'CARRIZO ALDAY', name: ' CECILIA YAMILA' },
    //   { dni: '37004796', lastname: 'IRRAZABAL', name: ' JANET ELIZABETH' },
    //   { dni: '43422777', lastname: 'MUÑOZ ESQUIVEL', name: ' ROCIO AILÍN' },
    //   { dni: '33766760', lastname: 'CASTRO GOMEZ', name: ' JOHANA VANESA' },
    //   { dni: '28161024', lastname: 'PIRAN', name: ' MARIA EUGENIA' },
    //   { dni: '42712372', lastname: 'RIVEROS CASTRO', name: ' GRECIA CAMILA' },
    //   { dni: '41014046', lastname: 'ZALAZAR LANDA', name: ' MARIA ISABEL' },
    //   { dni: '36253865', lastname: 'GARAY RODRIGUEZ', name: ' MAIRA GABRIELA' },
    //   { dni: '38461781', lastname: 'NAVARRO GOMEZ', name: ' FRANCISCO JAVIER' },
    //   { dni: '42163375', lastname: 'SARASPE TELLO', name: ' MAXIMILIANO' },
    //   {
    //     dni: '40995959',
    //     lastname: 'CARRIZO OCAMPO',
    //     name: ' MICAELA DEL CARMEN',
    //   },
    //   { dni: '40711704', lastname: 'CHANDIA', name: ' BRUNO NICOLÁS' },
    //   { dni: '95555678', lastname: 'AUGER IBAZETA', name: ' SALMA MILAY' },
    //   { dni: '33095313', lastname: 'FLORES', name: ' PAULA CECILIA' },
    //   { dni: '36253945', lastname: 'MARTINEZ', name: ' GABRIELA ABELINA' },
    //   { dni: '34329326', lastname: 'GUIDET', name: ' NATALIA ELIZABETH' },
    //   { dni: '40469688', lastname: 'CHIRINO ACOSTA', name: ' GILDA GUADALUPE' },
    //   { dni: '29161966', lastname: 'MORON', name: ' ANALIA ELIANA' },
    //   { dni: '32083693', lastname: 'ALBARRACIN', name: ' ANDREA VERONICA' },
    //   { dni: '34100889', lastname: 'MONCUNILL', name: ' NANCY EDITH' },
    //   { dni: '42005703', lastname: 'PASTEN', name: ' AGOSTINA' },
    //   {
    //     dni: '34916450',
    //     lastname: 'VELAZQUEZ VIDELA',
    //     name: ' BARBARA VANESA',
    //   },
    //   { dni: '43058406', lastname: 'RODRIGUEZ', name: ' ANA PAULA MILAGROS' },
    //   { dni: '42235433', lastname: 'PUCHOL DOÑA', name: ' CANDELA BELEN' },
    //   { dni: '42250048', lastname: 'ILLANES', name: ' KATHERINA' },
    //   {
    //     dni: '38218946',
    //     lastname: 'CORTEZ DOMINGUEZ',
    //     name: ' LUCIA GUADALUPE',
    //   },
    //   {
    //     dni: '39182238',
    //     lastname: 'BURGOS VALDEZ',
    //     name: ' FLORENCIA ALEJANDRA',
    //   },
    //   {
    //     dni: '42188264',
    //     lastname: 'GUEVARA IBARBE',
    //     name: ' ANTONELLA GEORGINA',
    //   },
    //   { dni: '34698547', lastname: 'BLANCO GONZALEZ', name: ' CLAUDIA LISETH' },
    //   { dni: '29302054', lastname: 'CAÑIZARES', name: ' ADRIANA ELIZABETH' },
    //   { dni: '34059896', lastname: 'VERA FLORES', name: ' CARLA MARIA LILIAN' },
    // ];

    // hola.forEach(async (element) => {
    //   const check = await this.findOneByDni(element.dni);
    //   if (!check) {
    //     this.create(element);
    //   }
    // });
    return await this.docenteRepository.find();
  }

  async findOne(id: string): Promise<Docente | null> {
    if (id) {
      const docente = await this.docenteRepository.findOneBy({ id });
      if (!docente) {
        return null;
        throw new NotFoundException(`Docente con ID ${id} no encontrado`);
      }
      return docente;
    } else {
      // console.log('id es undefined, no se realiza la consulta');
      return null;
      throw new NotFoundException(`Id , recibido con ID ${id} no encontrado`);
    }
  }

  async update(
    id: string,
    updateDocenteDto: UpdateDocenteDto,
  ): Promise<Docente | null> {
    try {
      const result = await this.docenteRepository.update(id, updateDocenteDto);
      if (result.affected === 0) {
        throw new NotFoundException(`Docente con ID ${id} no encontrado`);
      }
      return this.findOne(id);
    } catch (error) {
      if (error.errno === 1062) {
        throw new BadRequestException(
          `El docente con dni: ${updateDocenteDto.dni} ya existe.`,
        );
      }
      throw error;
    }
  }

  async remove(id: string): Promise<void> {
    const result = await this.docenteRepository.softDelete(id);
    if (result.affected === 0) {
      throw new NotFoundException(`Docente con ID ${id} no encontrado`);
    }
  }

  //nuevos

  async findDeletedDocenteByDni(dni: string): Promise<Docente | null> {
    const response = await this.docenteRepository.findOne({
      where: { dni },
      withDeleted: true,
    });

    if (response != null) {
      if (response.deletedAt != null) {
        return response;
      } else {
        return null;
      }
    } else {
      return response;
    }
  }

  async findOneByDni(dni: string): Promise<Docente | null> {
    if (dni) {
      const docente = await this.docenteRepository.findOne({ where: { dni } });
      if (!docente) {
        return null;
        throw new NotFoundException(`Docente con dni ${dni} no encontrado`);
      }
      return docente;
    } else {
      // console.log('id es undefined, no se realiza la consulta');
      return null;
      throw new NotFoundException(
        `dni , recibido con dni ${dni} no encontrado`,
      );
    }
  }

  async findAllOnlyDeleted(): Promise<Docente[]> {
    return this.docenteRepository
      .createQueryBuilder('docente')
      .where('docente.deletedAt IS NOT NULL')
      .getMany();
  }

  async findActive(): Promise<Docente[]> {
    return this.docenteRepository.find({ where: { deletedAt: null } });
  }
}
